# Generated by Django 5.2.7 on 2026-01-08 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssumptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('risk', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input_text', models.TextField(help_text='Original text analyzed')),
                ('input_text_length', models.IntegerField(default=0, help_text='Word count of input')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('analysis_type', models.CharField(choices=[('llm_local', 'Local LLM (Ollama)'), ('llm_enhanced', 'Claude Enhanced'), ('rule_based', 'Rule-Based')], default='llm_local', max_length=50)),
                ('model_used', models.CharField(default='neural-chat:7b', max_length=100)),
                ('total_assumptions', models.IntegerField(default=0)),
                ('high_risk_count', models.IntegerField(default=0)),
                ('medium_risk_count', models.IntegerField(default=0)),
                ('low_risk_count', models.IntegerField(default=0)),
                ('executive_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='engine_anal_created_d89691_idx'), models.Index(fields=['status'], name='engine_anal_status_cbf3d6_idx'), models.Index(fields=['analysis_type'], name='engine_anal_analysi_15cac4_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(default='summary', max_length=50)),
                ('report_format', models.CharField(choices=[('json', 'JSON'), ('pdf', 'PDF'), ('html', 'HTML'), ('markdown', 'Markdown')], default='json', max_length=20)),
                ('content', models.TextField(help_text='Serialized report content')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size_bytes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='engine.analysissession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color for UI display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ManyToManyField(related_name='tags', to='engine.analysissession')),
            ],
        ),
        migrations.CreateModel(
            name='Assumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumption_text', models.TextField(help_text='The actual assumption statement')),
                ('reasoning', models.TextField(help_text='Why this is considered an assumption')),
                ('category', models.CharField(choices=[('behavioral', 'Behavioral'), ('causal', 'Causal Relationship'), ('economic', 'Economic'), ('factual', 'Factual'), ('technical', 'Technical'), ('temporal', 'Temporal'), ('contextual', 'Contextual'), ('ethical', 'Ethical'), ('other', 'Other')], default='other', max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('confidence', models.FloatField(default=0.5, help_text='LLM confidence 0.0-1.0')),
                ('what_breaks', models.TextField(help_text='What fails if this assumption is false')),
                ('source_evidence', models.TextField(blank=True, help_text='Quote from text supporting this assumption')),
                ('position_in_analysis', models.IntegerField(help_text='Order detected in analysis (1-based)')),
                ('llm_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assumptions', to='engine.analysissession')),
            ],
            options={
                'ordering': ['position_in_analysis'],
            },
        ),
        migrations.CreateModel(
            name='AssumptionDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('depends_on', 'Depends On'), ('contradicts', 'Contradicts'), ('reinforces', 'Reinforces'), ('related_to', 'Related To')], default='depends_on', max_length=20)),
                ('strength', models.FloatField(default=0.5, help_text='Strength of relationship 0.0-1.0')),
                ('explanation', models.TextField(blank=True, help_text='Why these assumptions are related')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='engine.analysissession')),
                ('source_assumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depends_on_assumptions', to='engine.assumption')),
                ('target_assumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depended_by_assumptions', to='engine.assumption')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likelihood', models.FloatField(default=0.5, help_text='Likelihood of being incorrect (0.0-1.0)')),
                ('impact_if_false', models.FloatField(default=0.5, help_text='Impact if assumption is false (0.0-1.0)')),
                ('overall_risk_score', models.FloatField(default=0.5, help_text='Overall risk (likelihood * impact)')),
                ('mitigation_strategy', models.TextField(blank=True, help_text='How to validate or mitigate risk')),
                ('testing_recommendation', models.TextField(blank=True, help_text='How to test this assumption')),
                ('similar_assumptions', models.TextField(blank=True, help_text='JSON list of similar assumptions from history')),
                ('historical_accuracy', models.FloatField(blank=True, help_text='Historical accuracy rate if tracked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assumption', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='engine.assumption')),
            ],
        ),
        migrations.AddIndex(
            model_name='assumption',
            index=models.Index(fields=['session', 'position_in_analysis'], name='engine_assu_session_57de22_idx'),
        ),
        migrations.AddIndex(
            model_name='assumption',
            index=models.Index(fields=['risk_level'], name='engine_assu_risk_le_2fd97e_idx'),
        ),
        migrations.AddIndex(
            model_name='assumption',
            index=models.Index(fields=['category'], name='engine_assu_categor_23d031_idx'),
        ),
        migrations.AddIndex(
            model_name='assumptiondependency',
            index=models.Index(fields=['session'], name='engine_assu_session_87db1d_idx'),
        ),
        migrations.AddIndex(
            model_name='assumptiondependency',
            index=models.Index(fields=['dependency_type'], name='engine_assu_depende_2841c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assumptiondependency',
            unique_together={('source_assumption', 'target_assumption')},
        ),
    ]
