# Generated by Django 5.2.7 on 2026-01-08 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysissession',
            name='high_risk_count',
        ),
        migrations.RemoveField(
            model_name='analysissession',
            name='total_assumptions',
        ),
        migrations.AddField(
            model_name='analysissession',
            name='hallucination_count',
            field=models.PositiveIntegerField(default=0, help_text='Total hallucination signals detected'),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='hallucination_rate',
            field=models.FloatField(default=0.0, help_text='hallucination_rate = (unsupported + assumption + contradiction + schema_failures) / total_claims'),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='total_claims',
            field=models.PositiveIntegerField(default=0, help_text='Total claims parsed from LLM output'),
        ),
        migrations.CreateModel(
            name='HallucinationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(max_length=64)),
                ('event_type', models.CharField(choices=[('unsupported', 'Unsupported Claim'), ('assumption', 'Assumption Leakage'), ('contradiction', 'Internal Contradiction'), ('schema', 'Schema/Validation Failure'), ('user_flag', 'User-Flagged Issue')], max_length=16)),
                ('claim_text', models.TextField()),
                ('confidence_level', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallucination_events', to='engine.analysissession')),
            ],
        ),
    ]
